[PHP]

extension_dir = "ext"

extension=curl
extension=fileinfo
extension=mbstring
extension=openssl
extension=pdo_pgsql
extension=pgsql
extension=zip

memory_limit = 512M
upload_max_filesize = 50M
post_max_size = 50M
max_execution_time = 120

[Date]
date.timezone = "UTC"
